"use client";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppearLayer from "@/components/AppearLayer";
import Stair from "@/components/Stair";
import { ToastContainer } from "react-toastify";

const jetBrain = JetBrains_Mono({
  variable: "--font-jetbrain",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrain.variable} antialiased`}>
        <ToastContainer/>
        <Header />
        <Stair />
        <AppearLayer>{children}</AppearLayer>
        {/* {children} */}
      </body>
    </html>
  );
}
